### ISSUE TITLE
uwsgi socket type

### ISSUE THREAD

**Issue by spiderfingers** [dhalturin-test/askbot-vagrant-ansible#1]
https://github.com/dhalturin-test/askbot-vagrant-ansible/blob/70e2a0a03b5d3817eb5a2afbfd31db7a08f3a0a6/ansible/roles/setup/files/app.ini#L14-L15

я так понимаю, вы сначала хотели ходить в uwsgi через системный сокет, для этого сделали кастомный модуль для selinux, но что-то не получилось все равно, раз сейчас он работает через сетевой сокет?)

интересно, почему не получилось

**Comment by dhalturin-work** [comment]
Изначально да, делал через сокет, потом решил попробовать запустить на порту. Однако, при включенном селинуксе, без модуля не работает.

Селинукс выключать не стал, подключив тот самый модуль.
