### ISSUE TITLE
vbguest bad behavior

### ISSUE THREAD

**Issue by spiderfingers** [dhalturin-test/askbot-vagrant-ansible#2]
[JUST NOTICING]

плагин vbguest по дефолту обновляет то, что ему надо чтобы собрать модуль ядра. например обновляет kernel-devel, но не обновляет само ядро, что вызывает фейл

наверное стоило добавить в Vagrantfile
config.vbguest.auto_update = false

**Comment by dhalturin-work** [comment]
Кхм.. Просто указывая в конфиге provision - vagrant, я спотыкался о невозможность смонтировать директорию с манифестами внутрь виртуалки в `/tmp/vagrant-puppet/manifests-a11d1078b1b1f2e3bdea27312f6ba513`

Эт мне показалось странным, так как все тоже самое складывалось при развертывании виртуалки в `/vagrant`

Данное решение мне показалось правильным, на момент выполнения задания )
